
# Accessing Data within Pandas - Lab

## Introduction

In this lab, we'll look at a data set which contains information World cup matches. Let's use the pandas commands learned in the previous lecture to learn more about our data!

## Objectives
You will be able to:
* Understand and explain some key Pandas methods
* Access DataFrame data by using the label
* Perform boolean indexing on both Series and DataFrames
* Use simple selectors for series
* Set new Series and DataFrame inputs

## Load the data

Load the file `WorldCupMatches.csv` as a dataframe in Pandas

In [1]:
import pandas as pd

df = pd.read_csv('WorldCupMatches.csv')

## Common methods and attributes

Use the correct method to look at the first 7 rows of the data set.

In [2]:
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
5,1930.0,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3.0,0.0,Mexico,,9249.0,1.0,0.0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201.0,1095.0,CHI,MEX
6,1930.0,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4.0,0.0,Bolivia,,18306.0,0.0,0.0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201.0,1092.0,YUG,BOL

Look at the last 3 rows of the data set.

In [3]:
df.tail(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Get a concise summary of your data using `.info()`

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
Year                    852 non-null float64
Datetime                852 non-null object
Stage                   852 non-null object
Stadium                 852 non-null object
City                    852 non-null object
Home Team Name          852 non-null object
Home Team Goals         852 non-null float64
Away Team Goals         852 non-null float64
Away Team Name          852 non-null object
Win conditions          852 non-null object
Attendance              850 non-null float64
Half-time Home Goals    852 non-null float64
Half-time Away Goals    852 non-null float64
Referee                 852 non-null object
Assistant 1             852 non-null object
Assistant 2             852 non-null object
RoundID                 852 non-null float64
MatchID                 852 non-null float64
Home Team Initials      852 non-null object
Away Team Initials      852 non-null object
dtypes: float64(8), object(12)
memory usage: 714.5+ KB

Obtain a tuple representing the number of rows and number of columns

In [5]:
df.shape

(4572, 20)

Use the appropriate attribute to get the column names

In [6]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

## Selecting dataframe information

When looking at the dataframe's `.head()`, you might have noticed that the games are structured chronologically in the dataframe.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [7]:
df[2:5]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

Now, print all the info from game 5-9, but we're only interested to print out the "Home Team Name" and the "Away Team Name",

In [8]:
df.iloc[4:9,[5,8]]

  Home Team Name Away Team Name
4      Argentina         France
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru

Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [9]:
df.loc[(df['Stage']=='Group 3') & (df['Year']==1930.0)]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
8,1930.0,18 Jul 1930 - 14:30,Group 3,Estadio Centenario,Montevideo,Uruguay,1.0,0.0,Peru,,57735.0,0.0,0.0,LANGENUS Jean (BEL),BALWAY Thomas (FRA),CRISTOPHE Henry (BEL),201.0,1099.0,URU,PER
13,1930.0,21 Jul 1930 - 14:50,Group 3,Estadio Centenario,Montevideo,Uruguay,4.0,0.0,Romania,,70022.0,4.0,0.0,REGO Gilberto (BRA),WARNKEN Alberto (CHI),SAUCEDO Ulises (BOL),201.0,1100.0,URU,ROU

Let's repeat the command above, but now we only want to print out the attendance colum for the Group 3 games

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

In [10]:
df.loc[(df['Stage']=='Group 3') & (df['Year']==1930.0), 'Attendance']

3      2549.0
8     57735.0
13    70022.0
Name: Attendance, dtype: float64

Throughout the entire history of the world cup, How many Home games were played by the Netherlands?

In [11]:
df = df.drop_duplicates(keep='first')
df = df.drop([852])

In [12]:
len(df.loc[df['Home Team Name']=='Netherlands'])

29

How many games were playes by the Netherlands in total?

In [13]:
len(df.loc[df['Home Team Name']=='Netherlands'] + df.loc[df['Away Team Name']=='Netherlands'])

50

Next, let's try and figure out how many games the USA played in the 2014 world cup.

In [14]:
len((df.loc[(df['Home Team Name']=='USA') & (df['Year']==2014.0)]) + 
    (df.loc[(df['Away Team Name']=='USA') & (df['Year']==2014.0)]))

4

Now, let's try to find out how many countries participated in the 1986 world cup.

Hint 1: as a first step, create a new data set that only contain games in that year.

Hint 2: You can use `.unique()` to make sure you don't end up with duplicate country names.

In [15]:
new_df = df.loc[df['Year']==1986.0]
len(new_df['Home Team Initials'].unique())

24

In the world cup history, how matches had more than 5 goals in total?

In [16]:
len(df.loc[(df['Home Team Goals']+df['Away Team Goals']) > 5])

73

## Changing values and creating new columns

With the information you currently have in your `df`, create a new column "Half-time Goals".

In [18]:
df['Half-time Goals'] = df['Half-time Home Goals']+df['Half-time Away Goals']

Run the code below. You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [19]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ]

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

Imagine that for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

In [22]:
df.loc[df['Home Team Name']=='Korea Republic', 'Home Team Name'] = 'Korea'
df.loc[df['Home Team Name']=='Korea DPR', 'Home Team Name'] = 'Korea'
df.loc[df['Away Team Name']=='Korea Republic', 'Away Team Name'] = 'Korea'
df.loc[df['Away Team Name']=='Korea DPR', 'Away Team Name'] = 'Korea'

df.loc[df['Home Team Initials']=='KOR', 'Home Team Initials'] = 'NSK'
df.loc[df['Home Team Initials']=='PRK', 'Home Team Initials'] = 'NSK'
df.loc[df['Away Team Initials']=='KOR', 'Away Team Initials'] = 'NSK'
df.loc[df['Away Team Initials']=='PRK', 'Away Team Initials'] = 'NSK'

Make sure to verify your answer!

In [23]:
df.loc[df["Home Team Name"].str.contains('Korea'), "Home Team Name" ]

179    Korea
187    Korea
374    Korea
386    Korea
434    Korea
444    Korea
480    Korea
524    Korea
593    Korea
609    Korea
635    Korea
642    Korea
655    Korea
710    Korea
753    Korea
802    Korea
818    Korea
Name: Home Team Name, dtype: object

In [24]:
df.loc[df['Home Team Name']=='Korea']

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Half-time Goals
179,1966.0,15 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1.0,1.0,Chile,,...,0.0,1.0,KANDIL Aly Hussein (EGY),CRAWFORD William (SCO),FINNEY Jim (ENG),238.0,1609.0,NSK,CHI,1.0
187,1966.0,19 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1.0,0.0,Italy,,...,1.0,0.0,SCHWINTE Pierre (FRA),ADAIR John (NIR),TAYLOR John (ENG),238.0,1679.0,NSK,ITA,1.0
374,1986.0,05 Jun 1986 - 16:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Korea,1.0,1.0,Bulgaria,,...,0.0,1.0,AL SHANAR Fallaj Khuzam (KSA),IGNA Ioan (ROU),BUTENKO Valeri (RUS),308.0,460.0,NSK,BUL,1.0
386,1986.0,10 Jun 1986 - 12:00,Group A,Cuauhtemoc,Puebla,Korea,2.0,3.0,Italy,,...,0.0,1.0,SOCHA David (USA),URREA Joaquin (MEX),AL SHARIF Jamal (SYR),308.0,643.0,NSK,ITA,1.0
434,1990.0,17 Jun 1990 - 21:00,Group E,Dacia Arena,Udine,Korea,1.0,3.0,Spain,,...,1.0,1.0,JACOME GUERRERO Elias V. (ECU),MAGNI Pierluigi (ITA),LOUSTAU Juan (ARG),322.0,175.0,NSK,ESP,2.0
444,1990.0,21 Jun 1990 - 17:00,Group E,Friuli,Udine,Korea,0.0,1.0,Uruguay,,...,0.0,0.0,LANESE Tullio (ITA),DIRAMBA Jean Fidele (GAB),JOUINI Neji (TUN),322.0,290.0,NSK,URU,0.0
480,1994.0,23 Jun 1994 - 19:30,Group C,Foxboro Stadium,Boston,Korea,0.0,0.0,Bolivia,,...,0.0,0.0,MOTTRAM Leslie (SCO),MATTHYS Luc (BEL),EVERSTIG Mikael (SWE),337.0,3065.0,NSK,BOL,0.0
524,1998.0,13 Jun 1998 - 17:30,Group E,Stade de Gerland,Lyon,Korea,1.0,3.0,Mexico,,...,1.0,0.0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014.0,8732.0,NSK,MEX,1.0
593,2002.0,04 Jun 2002 - 20:30,Group D,Busan Asiad Main Stadium,Busan,Korea,2.0,0.0,Poland,,...,1.0,0.0,RUIZ Oscar (COL),DORIRI Elise (VAN),LINDBERG Leif (SWE),43950100.0,43950014.0,NSK,POL,1.0
609,2002.0,10 Jun 2002 - 15:30,Group D,Daegu World Cup Stadium,Daegu,Korea,1.0,1.0,USA,,...,0.0,1.0,MEIER Urs (SUI),BEREUTER Egon (AUT),TOMUSANGE Ali (UGA),43950100.0,43950030.0,NSK,USA,1.0
635,2002.0,18 Jun 2002 - 20:30,Round of 16,Daejeon World Cup Stadium,Daejeon,Korea,2.0,1.0,Italy,Win on Golden Goal,...,0.0,0.0,MORENO Byron (ECU),RATTALINO Jorge (ARG),SZEKELY Ferenc (HUN),43950200.0,43950056.0,NSK,ITA,0.0
642,2002.0,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea,2.0,3.0,Turkey,,...,1.0,3.0,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500.0,43950063.0,NSK,TUR,4.0
655,2006.0,13 Jun 2006 - 15:00,Group G,"FIFA World Cup Stadium, Frankfurt",Frankfurt/Main,Korea,2.0,1.0,Togo,,...,0.0,1.0,POLL Graham (ENG),SHARP Philip (ENG),TURNER Glenn (ENG),97410100.0,97410014.0,NSK,TOG,1.0
710,2010.0,12 Jun 2010 - 13:30,Group B,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea,2.0,0.0,Greece,,...,1.0,0.0,HESTER Michael (NZL),HINTZ Jan Hendrik (NZL),MAKASINI Tevita (TGA),249722.0,300061459.0,NSK,GRE,1.0
753,2010.0,25 Jun 2010 - 16:00,Group G,Mbombela Stadium,Nelspruit,Korea,0.0,3.0,C�te d'Ivoire,,...,0.0,2.0,Alberto UNDIANO MALLENCO (ESP),MARTINEZ Fermin (ESP),YUSTE Juan (ESP),249722.0,300061486.0,NSK,CIV,2.0
802,2014.0,22 Jun 2014 - 16:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea,2.0,4.0,Algeria,,...,0.0,3.0,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931.0,300186495.0,NSK,ALG,3.0
818,2014.0,26 Jun 2014 - 17:00,Group H,Arena de Sao Paulo,Sao Paulo,Korea,0.0,1.0,Belgium,,...,0.0,0.0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255931.0,300186480.0,NSK,BEL,0.0